# Generated by Django 3.0.8 on 2021-04-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data', '0002_weatherresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='day_weather',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='day_weather_short',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='day_wind_direction',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='day_wind_power',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='night_weather',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='night_weather_short',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='night_wind_direction',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='night_wind_power',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
