# Generated by Django 3.0.8 on 2020-07-30 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0002_auto_20200727_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_weather', models.CharField(max_length=20)),
                ('day_weather_code', models.CharField(max_length=2)),
                ('day_weather_short', models.CharField(max_length=20)),
                ('day_wind_direction', models.CharField(max_length=20)),
                ('day_wind_direction_code', models.CharField(max_length=4)),
                ('day_wind_power', models.SmallIntegerField()),
                ('day_wind_power_code', models.CharField(max_length=2)),
                ('max_degree', models.FloatField()),
                ('min_degree', models.FloatField()),
                ('night_weather', models.CharField(max_length=20)),
                ('night_weather_code', models.CharField(max_length=2)),
                ('night_weather_short', models.CharField(max_length=20)),
                ('night_wind_direction', models.CharField(max_length=20)),
                ('night_wind_direction_code', models.CharField(max_length=2)),
                ('night_wind_power', models.CharField(max_length=20)),
                ('night_wind_power_code', models.CharField(max_length=2)),
                ('time', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Region')),
            ],
        ),
    ]
