# Generated by Django 3.0.8 on 2020-08-05 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_auto_20200727_2021'),
        ('weather_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Region')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
