# Generated by Django 3.0.8 on 2021-04-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data', '0003_auto_20210429_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='day_weather',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='day_weather_code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='day_weather_short',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='day_wind_direction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='day_wind_power',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='day_wind_power_code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='night_weather',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='night_weather_code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='night_weather_short',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='night_wind_direction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='night_wind_direction_code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='night_wind_power',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='night_wind_power_code',
            field=models.CharField(max_length=4),
        ),
    ]
