# Generated by Django 3.0.8 on 2020-08-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_auto_20200727_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='short_name',
            field=models.CharField(default='', max_length=30, verbose_name='区域别名'),
            preserve_default=False,
        ),
    ]
