# Generated by Django 3.0.8 on 2020-07-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='区域编号')),
                ('name', models.CharField(max_length=30, verbose_name='区域名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='region.Region', verbose_name='父级区域')),
            ],
        ),
    ]
